name: pa3030_env
channels:
  - conda-forge
  - nodefaults  # Optional: Prevents conflicts with the main Anaconda channel
dependencies:
  - python=3.12  # Pinned for stability
  - hazelbean

  - pip:
    # ACTUAL local development: points to the folder on your disk
    - "-e ../pa3030_dev"